export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAIL = 'GET_CONTACTS_FAIL';

export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
export const CREATE_CONTACT_FAIL = 'CREATE_CONTACT_FAIL';

export const EDIT_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS';
export const EDIT_CONTACT_FAIL = 'EDIT_CONTACT_FAIL';

export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAIL = 'DELETE_CONTACT_FAIL';

export const OPEN_CALL_HISTORY = 'OPEN_CALL_HISTORY';
export const CLOSE_CALL_HISTORY = 'CLOSE_CALL_HISTORY';

export const GET_CALL_HISTORY_SUCCESS = 'GET_CALL_HISTORY_SUCCESS';
export const GET_CALL_HISTORY_FAIL = 'GET_CALL_HISTORY_FAIL';

export const MAKE_CALL_SUCCESS = 'MAKE_CALL_SUCCESS';
export const MAKE_CALL_FAIL = 'MAKE_CALL_FAIL';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const OPEN_DROPDOWN = 'OPEN_DROPDOWN';
export const CLOSE_DROPDOWN = 'CLOSE_DROPDOWN';
