export const CHANGE_CONTACT_NAME = 'CHANGE_CONTACT_NAME';
export const CHANGE_CONTACT_PHONE = 'CHANGE_CONTACT_PHONE';
export const CLEAR_CONTACT_INFO = 'CLEAR_CONTACT_INFO';

export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACT_INFO_SUCCESS = 'GET_CONTACT_INFO_SUCCESS';
export const GET_CALL_HISTORY_SUCCESS = 'GET_CALL_HISTORY_SUCCESS';
export const MAKE_CALL_SUCCESS = 'MAKE_CALL_SUCCESS';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const OPEN_DROPDOWN = 'OPEN_DROPDOWN';
export const CLOSE_DROPDOWN = 'CLOSE_DROPDOWN';
