export const GET_CONTACTS = 'GET_CONTACTS';
export const SEARCH_CONTACTS = 'SEARCH_CONTACTS';
export const CREATE_CONTACT = 'CREATE_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';

export const OPEN_CALL_HISTORY = 'OPEN_CALL_HISTORY';
export const CLOSE_CALL_HISTORY = 'CLOSE_CALL_HISTORY';
export const GET_CALL_HISTORY = 'GET_CALL_HISTORY';
export const MAKE_CALL = 'MAKE_CALL';

export const GO_TO_PAGE = 'GO_TO_PAGE';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
